import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { GitCommit, X, ChevronRight, ChevronDown, CheckCircle2, Circle, Send, MoreHorizontal } from 'lucide-react';

interface AgentSidebarProps {
  onSuggestDiff: (code: string) => void;
  onClose: () => void;
  currentCode: string;
}

export default function AgentSidebar({ onSuggestDiff, onClose, currentCode }: AgentSidebarProps) {
  const [isPlanExpanded, setIsPlanExpanded] = useState(true);
  const [chatInput, setChatInput] = useState('');
  const [messages, setMessages] = useState<{ role: 'user'|'agent', text: string }[]>([
    { role: 'agent', text: 'I am ready to help you edit this file. What would you like to build or refactor?' }
  ]);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = () => {
    if (!chatInput.trim()) return;
    const input = chatInput.trim();
    setChatInput('');
    setMessages(prev => [...prev, { role: 'user', text: input }]);
    
    // Simulate Agent Delay and Thought Process
    setTimeout(() => {
      setMessages(prev => [...prev, { role: 'agent', text: 'I am analyzing the file to fulfill your request...' }]);
      
      // Simulate providing a code edit diff after 2 seconds
      setTimeout(() => {
        setMessages(prev => [...prev, { role: 'agent', text: 'I have prepared an implementation plan and the necessary code changes. Review the diff in the editor.' }]);
        
        // Very basic mock diff generation by just appending a comment 
        const newCode = currentCode.includes('// AI-Suggestion') 
          ? currentCode.replace('// AI-Suggestion: Add username field here', 'OutlinedTextField(\n            value = "",\n            onValueChange = {},\n            label = { Text("Username") }\n        )') 
          : currentCode + '\n// This was auto-generated by the Coder Agent';
          
        onSuggestDiff(newCode);
      }, 2000);
    }, 500);
  };

  return (
    <div className="w-[300px] h-full flex flex-col shrink-0 border-l border-[var(--border-color)] bg-[var(--bg-secondary)] overflow-hidden">
      {/* Sidebar Header */}
      <div className="flex items-center justify-between px-4 py-2 text-[11px] font-semibold text-[var(--text-secondary)] uppercase tracking-wider border-b border-[var(--border-color)]">
        <span>Open Agent Manager</span>
        <div className="flex items-center gap-1">
          <button className="p-1 hover:bg-[var(--bg-glass-hover)] rounded">
            <MoreHorizontal className="w-3.5 h-3.5" />
          </button>
          <button onClick={onClose} className="p-1 hover:bg-[var(--bg-glass-hover)] hover:text-red-500 rounded transition-colors">
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto flex flex-col">
        {/* Implementation Plan Accordion (Mimicking the Screenshot) */}
        <div className="mt-2 mx-2">
          <button 
            onClick={() => setIsPlanExpanded(!isPlanExpanded)}
            className="w-full flex items-center justify-between px-3 py-2 rounded-lg bg-[var(--bg-glass)] hover:bg-[var(--bg-glass-hover)] border border-[var(--border-color)] transition-colors"
          >
            <div className="flex items-center gap-2">
              <GitCommit className="w-3.5 h-3.5 text-agent-designer" />
              <span className="text-xs font-medium text-[var(--text-primary)]">Implementation Plan</span>
            </div>
            {isPlanExpanded ? <ChevronDown className="w-3.5 h-3.5 text-text-muted" /> : <ChevronRight className="w-3.5 h-3.5 text-text-muted" />}
          </button>
          
          <AnimatePresence>
            {isPlanExpanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="overflow-hidden"
              >
                <div className="px-3 py-3 border-l-2 border-l-agent-designer/30 ml-2 mt-1 flex flex-col gap-2">
                  <div className="flex items-start gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 mt-0.5 shrink-0" />
                    <span className="text-[11px] text-[var(--text-muted)]">Analyze current screen state.</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <Circle className="w-3.5 h-3.5 text-blue-500 mt-0.5 shrink-0" />
                    <span className="text-[11px] text-[var(--text-primary)]">Implement user requested changes.</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <Circle className="w-3.5 h-3.5 text-[var(--text-muted)] mt-0.5 shrink-0" />
                    <span className="text-[11px] text-[var(--text-muted)] opacity-70">Review tests.</span>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Conversation Feed */}
        <div className="flex-1 px-3 py-4 space-y-4">
          {messages.map((msg, i) => (
            <div key={i} className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
              <span className="text-[10px] font-mono text-[var(--text-muted)] mb-1 ml-1">
                {msg.role === 'user' ? 'You' : 'Nexus Agent'}
              </span>
              <div className={`px-3 py-2 text-xs leading-relaxed max-w-[90%] shadow-sm ${
                msg.role === 'user' 
                  ? 'bg-blue-500 text-white rounded-t-xl rounded-bl-xl' 
                  : 'bg-[var(--bg-void)] border border-[var(--border-color)] text-[var(--text-primary)] rounded-t-xl rounded-br-xl'
              }`}>
                {msg.text}
              </div>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input Box */}
      <div className="p-3 bg-[var(--bg-secondary)] border-t border-[var(--border-color)]">
        <div className="flex items-center gap-2 px-3 py-2 bg-[var(--bg-void)] border border-[var(--border-color)] rounded-lg focus-within:border-blue-500 focus-within:ring-1 focus-within:ring-blue-500 transition-shadow">
          <input
            type="text"
            value={chatInput}
            onChange={(e) => setChatInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Ask anything (⌘L), @ to mention..."
            className="flex-1 bg-transparent text-xs text-[var(--text-primary)] placeholder-[var(--text-muted)] outline-none"
          />
          <button
            onClick={handleSend}
            disabled={!chatInput.trim()}
            className="w-6 h-6 flex items-center justify-center text-blue-500 hover:text-blue-600 disabled:opacity-30 transition-colors"
          >
            <Send className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </div>
  );
}
