import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { GitCommit, X, ChevronRight, ChevronDown, CheckCircle2, Circle, Minimize2, Send, WandSparkles } from 'lucide-react';
import GlassPanel from '../ui/GlassPanel';

interface FloatingAgentWindowProps {
  onSuggestDiff: (code: string) => void;
  onClose: () => void;
  currentCode: string;
}

export default function FloatingAgentWindow({ onSuggestDiff, onClose, currentCode }: FloatingAgentWindowProps) {
  const [isMinimized, setIsMinimized] = useState(false);
  const [isPlanExpanded, setIsPlanExpanded] = useState(true);
  const [chatInput, setChatInput] = useState('');
  const [messages, setMessages] = useState<{ role: 'user'|'agent', text: string }[]>([
    { role: 'agent', text: 'I am ready to help you edit this file. What would you like to build or refactor?' }
  ]);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = () => {
    if (!chatInput.trim()) return;
    const input = chatInput.trim();
    setChatInput('');
    setMessages(prev => [...prev, { role: 'user', text: input }]);
    
    // Simulate Agent Delay and Thought Process
    setTimeout(() => {
      setMessages(prev => [...prev, { role: 'agent', text: 'I am analyzing the file to fulfill your request...' }]);
      
      // Simulate providing a code edit diff after 2 seconds
      setTimeout(() => {
        setMessages(prev => [...prev, { role: 'agent', text: 'I have prepared an implementation plan and the necessary code changes. Review the diff in the editor.' }]);
        
        // Very basic mock diff generation by just appending a comment 
        // In a real implementation this would stream the exact text from the LLM
        const newCode = currentCode.includes('// AI-Suggestion') 
          ? currentCode.replace('// AI-Suggestion: Add username field here', 'OutlinedTextField(\n            value = "",\n            onValueChange = {},\n            label = { Text("Username") }\n        )') 
          : currentCode + '\n// This was auto-generated by the Coder Agent';
          
        onSuggestDiff(newCode);
      }, 2000);
    }, 500);
  };

  if (isMinimized) {
    return (
      <motion.div
        drag
        dragMomentum={false}
        className="absolute bottom-10 right-10 z-50 cursor-grab active:cursor-grabbing"
      >
        <button 
          onClick={() => setIsMinimized(false)}
          className="w-12 h-12 rounded-full bg-void shadow-2xl border border-glass-border flex items-center justify-center relative group hover:scale-105 transition-transform"
        >
          <div className="absolute inset-0 rounded-full bg-agent-coder/20 animate-pulse pointer-events-none" />
          <WandSparkles className="w-5 h-5 text-agent-coder" />
        </button>
      </motion.div>
    );
  }

  return (
    <motion.div
      drag
      dragConstraints={{ left: 50, top: 50, right: window.innerWidth - 450, bottom: window.innerHeight - 500 }}
      dragMomentum={false}
      initial={{ opacity: 0, scale: 0.95, y: 20 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      className="absolute top-20 right-20 w-[400px] bg-void/90 backdrop-blur-2xl border border-glass-border/50 rounded-xl shadow-2xl flex flex-col z-50 pointer-events-auto"
      style={{ maxHeight: 'calc(100vh - 120px)' }}
    >
      {/* Top Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-glass-border cursor-grab active:cursor-grabbing hover:bg-white/[0.02] transition-colors rounded-t-xl group">
        <div className="flex items-center gap-3">
          <div className="w-2 h-2 rounded-full bg-agent-coder animate-pulse shadow-[0_0_10px_rgba(33,150,243,0.5)]" />
          <h2 className="text-xs font-semibold text-text-secondary tracking-wide flex items-center gap-2">
            NEXUS Coder <span className="text-[10px] font-mono text-text-muted px-1.5 py-0.5 rounded bg-glass">(Working Tree)</span>
          </h2>
        </div>
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button onClick={() => setIsMinimized(true)} className="p-1.5 rounded hover:bg-glass text-text-muted hover:text-white transition-colors">
            <Minimize2 className="w-3 h-3" />
          </button>
          <button onClick={onClose} className="p-1.5 rounded hover:bg-glass text-text-muted hover:text-red-400 transition-colors">
            <X className="w-3 h-3" />
          </button>
        </div>
      </div>

      {/* Body Area */}
      <div className="flex-1 overflow-y-auto flex flex-col pb-2">
        
        {/* Implementation Plan Accordion (Mimicking the Screenshot) */}
        <div className="mt-3 mx-3">
          <button 
            onClick={() => setIsPlanExpanded(!isPlanExpanded)}
            className="w-full flex items-center justify-between px-3 py-2 rounded-lg bg-glass/30 hover:bg-glass/50 border border-glass-border/50 transition-colors"
          >
            <div className="flex items-center gap-2">
              <GitCommit className="w-3.5 h-3.5 text-agent-designer" />
              <span className="text-xs font-medium text-text-secondary">Implementation Plan</span>
            </div>
            {isPlanExpanded ? <ChevronDown className="w-3.5 h-3.5 text-text-muted" /> : <ChevronRight className="w-3.5 h-3.5 text-text-muted" />}
          </button>
          
          <AnimatePresence>
            {isPlanExpanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="overflow-hidden"
              >
                <div className="px-3 py-3 border-l-2 border-l-agent-designer/30 ml-2 mt-1 flex flex-col gap-2">
                  <div className="flex items-start gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-status-done mt-0.5 shrink-0" />
                    <span className="text-[11px] text-text-muted">Analyze current LoginScreen.kt compose state.</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <Circle className="w-3.5 h-3.5 text-agent-coder mt-0.5 shrink-0" />
                    <span className="text-[11px] text-text-secondary">Inject OutlinedTextField for username input.</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <Circle className="w-3.5 h-3.5 text-text-muted/50 mt-0.5 shrink-0" />
                    <span className="text-[11px] text-text-muted/50">Add secure password field & login button.</span>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Conversation Feed */}
        <div className="flex-1 px-4 py-4 space-y-4">
          {messages.map((msg, i) => (
            <div key={i} className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
              <span className="text-[10px] font-mono text-text-muted mb-1 ml-1">
                {msg.role === 'user' ? 'You' : 'NEXUS Agent'}
              </span>
              <div className={`px-3 py-2 rounded-xl text-xs leading-relaxed max-w-[90%] ${
                msg.role === 'user' 
                  ? 'bg-agent-coder/20 text-text-primary border border-agent-coder/30 rounded-tr-sm' 
                  : 'bg-glass border border-glass-border text-text-secondary rounded-tl-sm'
              }`}>
                {msg.text}
              </div>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input Bar (Anchored at the bottom of the widget) */}
      <div className="p-3 bg-void/50 border-t border-glass-border/50 rounded-b-xl backdrop-blur-md">
        <GlassPanel className="flex items-center gap-2 px-3 py-1.5 focus-within:ring-1 focus-within:ring-agent-coder/50 transition-shadow">
          <input
            type="text"
            value={chatInput}
            onChange={(e) => setChatInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Ask anything, @ to mention, / for workflows"
            className="flex-1 bg-transparent py-1.5 text-xs text-white placeholder:text-text-muted/70 outline-none"
          />
          <button
            onClick={handleSend}
            disabled={!chatInput.trim()}
            className="w-6 h-6 rounded-full bg-agent-coder/20 flex items-center justify-center text-agent-coder hover:bg-agent-coder/40 disabled:opacity-30 disabled:hover:bg-agent-coder/20 transition-colors"
          >
            <Send className="w-3 h-3 ml-0.5" />
          </button>
        </GlassPanel>
      </div>
    </motion.div>
  );
}
